DROP DATABASE IF EXISTS meetingDB;
CREATE DATABASE meetingDB;
USE meetingDB;

CREATE TABLE room(
ID INT PRIMARY KEY AUTO_INCREMENT,
`name` VARCHAR(50) NOT NULL,
`description` VARCHAR(100)
);

CREATE TABLE meeting(
ID INT PRIMARY KEY AUTO_INCREMENT,
`name` VARCHAR(50) NOT NULL,
`time` DATETIME NOT NULL,
roomID INT NOT NULL,
FOREIGN KEY (roomID) REFERENCES room(id));

CREATE TABLE employee(
ID INT PRIMARY KEY AUTO_INCREMENT,
firstName VARCHAR(50) NOT NULL,
lastName VARCHAR(50) NOT NULL
);

CREATE TABLE meeting_employee(
meetingID INT NOT NULL,
employeeID INT NOT NULL,
PRIMARY KEY(meetingID, employeeID),
FOREIGN KEY (meetingID) REFERENCES meeting(ID),
FOREIGN KEY (employeeID) REFERENCES employee(ID)
);